Blackthorn/force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackthorn/force-app/main/default/objects/EventAttendee__c/EventAttendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventeAttendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventAttendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>EventeAttendees</relationshipLabel>
    <relationshipName>AttendeesEvent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RecordListController.cls
public with sharing class RecordListController {
    
    @AuraEnabled
    public static List<Attendee__c> getRecords(Id recordId){
        //Usar EventAttendeeSelector
        return Database.query('Select Id, Name, Birthday__c From Attendee__c ');
    }

    @AuraEnabled
    public static string deleteRecord(Id recordId){
        try {
            //Usar EventAttendeeSelector
            delete [SELECT Id FROM EventAttendee__c Where Id =: recordId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return 'Ok';
    }
}