Blackthorn/force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackthorn/force-app/main/default/objects/EventAttendee__c/EventAttendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventeAttendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventAttendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>EventeAttendees</relationshipLabel>
    <relationshipName>AttendeesEvent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventAttendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>EventeAttendees</relationshipLabel>
    <relationshipName>EventAttendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventAttendeeSelector.cls
public class EventAttendeeSelector extends fflib_SObjectSelector {
 
    public Schema.SObjectType getSObjectType(){
        return EventAttendee__c.sObjectType;
    }
    public EventAttendeeSelector() {
        super(false);
    }
    
    public EventAttendeeSelector(Boolean includeFieldSetFields) {
        super(includeFieldSetFields);
    }
 
    public List<Schema.SObjectField> getSObjectFieldList(){
      return new List<Schema.SObjectField> {
         EventAttendee__c.Id,
         EventAttendee__c.Name,
         EventAttendee__c.Event__c,
         EventAttendee__c.Attendee__c
        };
    }

    public List<Event__c> selectById(Set<Id> idSet){
        return (List<Event__c>) selectSObjectsById(idSet);
    }
   
    public List<EventAttendee__c> selectByEventAndAttendees(Set<Id> eventIds, Set<Id> attendeeIds) {
        String query = String.format(
            'select {0} from {1} ' +
            'where Event__c =: eventIds AND Attendee__c =: attendeeIds',
            new List<String> {
                getFieldListString(),
                getSObjectName(),
                getOrderBy()
            }
            );
        return (List<EventAttendee__c>) Database.query(query);
    }

    public List<EventAttendee__c> selectByEvent(Set<Id> eventIds) {
        String query = String.format(
            'select {0} from {1} ' +
            'where Event__c =: eventIds ',
            new List<String> {
                getFieldListString(),
                getSObjectName(),
                getOrderBy()
            }
            );
        return (List<EventAttendee__c>) Database.query(query);
    }
}